// examples/inertia-react/client/src/components/AppLayout.tsx
import { Link, usePage } from "@inertiajs/react";
import type { ReactNode } from "react";
import { toggleTheme } from "../styles/theme.js";
import { BlokLogo, ThemeIcons } from "./BlokLogo.js";

/**
 * The persistent layout. Inertia keeps this component MOUNTED across visits
 * (`Page.layout = (page) => <AppLayout>{page}</AppLayout>`), so the header,
 * the theme toggle and any state they hold survive navigation — only the page
 * below swaps.
 */

interface NavItem {
	href: string;
	label: string;
	external?: boolean;
}

const NAV: NavItem[] = [
	{ href: "/", label: "Dashboard" },
	{ href: "/orders/new", label: "Orders" },
	{ href: "https://blok.build", label: "Docs", external: true },
];

function navLinks(url: string, onNavigate?: () => void): ReactNode {
	return NAV.map((item) =>
		item.external === true ? (
			<a key={item.href} href={item.href} rel="noreferrer">
				{item.label}
			</a>
		) : (
			<Link key={item.href} href={item.href} onClick={onNavigate} aria-current={url === item.href ? "page" : undefined}>
				{item.label}
			</Link>
		),
	);
}

export function AppLayout({ children }: { children: ReactNode }) {
	const { url, props } = usePage<{ auth?: { email?: string } }>();
	const email = props.auth?.email;

	return (
		<div className="blok-shell">
			<header className="blok-header">
				<div className="blok-container blok-header__inner">
					<Link href="/" className="blok-brand" aria-label="Blok — dashboard">
						<BlokLogo height={22} />
					</Link>

					<nav className="blok-nav" aria-label="Primary">
						{navLinks(url)}
					</nav>

					<div className="blok-header__end">
						{email === undefined ? null : <span className="blok-user">{email}</span>}
						<button
							type="button"
							className="blok-btn blok-btn--ghost blok-btn--icon blok-theme-toggle"
							onClick={() => toggleTheme()}
							aria-label="Switch between light and dark theme"
						>
							<ThemeIcons />
						</button>

						{/* A native <details>: the 375px menu ships no JavaScript. */}
						<details className="blok-menu">
							<summary className="blok-btn blok-btn--ghost blok-btn--icon" aria-label="Menu">
								<svg
									width="16"
									height="16"
									viewBox="0 0 24 24"
									stroke="currentColor"
									strokeWidth="2"
									strokeLinecap="round"
									aria-hidden="true"
								>
									<path d="M3 6h18M3 12h18M3 18h18" />
								</svg>
							</summary>
							<nav className="blok-menu__panel blok-nav" aria-label="Primary, compact">
								{navLinks(url)}
							</nav>
						</details>
					</div>
				</div>
			</header>

			<main className="blok-main">
				<div className="blok-container">{children}</div>
			</main>

			<footer className="blok-footer">
				<div className="blok-container blok-footer__inner">
					<BlokLogo variant="mark" height={16} />
					<span>Built with Blok</span>
					<span aria-hidden="true">·</span>
					<a href="https://blok.build" rel="noreferrer">
						blok.build
					</a>
					<span aria-hidden="true">·</span>
					<a href="https://github.com/well-prado/blok" rel="noreferrer">
						GitHub
					</a>
					<span aria-hidden="true">·</span>
					<a href="https://deskree.com" rel="noreferrer">
						Deskree
					</a>
				</div>
			</footer>
		</div>
	);
}

/** Sugar for `Page.layout = …` — one import per page instead of two. */
export const appLayout = (page: ReactNode): ReactNode => <AppLayout>{page}</AppLayout>;

// examples/inertia-vue/client/src/components/AppLayout.vue
<script setup lang="ts">
/**
 * The persistent layout. Inertia keeps this component MOUNTED across visits
 * (`defineOptions({ layout: AppLayout })` in each page), so the header and the
 * theme toggle survive navigation — only the page below swaps.
 */
import { Link, usePage } from "@inertiajs/vue3";
import { computed } from "vue";
import { toggleTheme } from "../styles/theme.js";
import BlokLogo from "./BlokLogo.vue";

interface NavItem {
	href: string;
	label: string;
	external?: boolean;
}

const NAV: NavItem[] = [
	{ href: "/", label: "Dashboard" },
	{ href: "https://blok.build", label: "Docs", external: true },
	{ href: "https://github.com/well-prado/blok", label: "GitHub", external: true },
];

const page = usePage<{ auth?: { email?: string } }>();
const email = computed(() => page.props.auth?.email);
</script>

<template>
	<div class="blok-shell">
		<header class="blok-header">
			<div class="blok-container blok-header__inner">
				<Link href="/" class="blok-brand" aria-label="Blok — dashboard">
					<BlokLogo :height="22" />
				</Link>

				<nav class="blok-nav" aria-label="Primary">
					<template v-for="item in NAV" :key="item.href">
						<a v-if="item.external" :href="item.href" rel="noreferrer">{{ item.label }}</a>
						<Link v-else :href="item.href" :aria-current="page.url === item.href ? 'page' : undefined">
							{{ item.label }}
						</Link>
					</template>
				</nav>

				<div class="blok-header__end">
					<span v-if="email" class="blok-user">{{ email }}</span>
					<button
						type="button"
						class="blok-btn blok-btn--ghost blok-btn--icon blok-theme-toggle"
						aria-label="Switch between light and dark theme"
						@click="toggleTheme()"
					>
						<svg
							class="blok-icon--moon"
							width="16"
							height="16"
							viewBox="0 0 24 24"
							fill="none"
							stroke="currentColor"
							stroke-width="2"
							stroke-linecap="round"
							stroke-linejoin="round"
							aria-hidden="true"
						>
							<path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79Z" />
						</svg>
						<svg
							class="blok-icon--sun"
							width="16"
							height="16"
							viewBox="0 0 24 24"
							fill="none"
							stroke="currentColor"
							stroke-width="2"
							stroke-linecap="round"
							stroke-linejoin="round"
							aria-hidden="true"
						>
							<circle cx="12" cy="12" r="4" />
							<path
								d="M12 2v2m0 16v2M4.93 4.93l1.41 1.41m11.32 11.32 1.41 1.41M2 12h2m16 0h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"
							/>
						</svg>
					</button>

					<!-- A native <details>: the 375px menu ships no JavaScript. -->
					<details class="blok-menu">
						<summary class="blok-btn blok-btn--ghost blok-btn--icon" aria-label="Menu">
							<svg
								width="16"
								height="16"
								viewBox="0 0 24 24"
								stroke="currentColor"
								stroke-width="2"
								stroke-linecap="round"
								aria-hidden="true"
							>
								<path d="M3 6h18M3 12h18M3 18h18" />
							</svg>
						</summary>
						<nav class="blok-menu__panel blok-nav" aria-label="Primary, compact">
							<template v-for="item in NAV" :key="item.href">
								<a v-if="item.external" :href="item.href" rel="noreferrer">{{ item.label }}</a>
								<Link v-else :href="item.href">{{ item.label }}</Link>
							</template>
						</nav>
					</details>
				</div>
			</div>
		</header>

		<main class="blok-main">
			<div class="blok-container"><slot /></div>
		</main>

		<footer class="blok-footer">
			<div class="blok-container blok-footer__inner">
				<BlokLogo variant="mark" :height="16" />
				<span>Built with Blok</span>
				<span aria-hidden="true">·</span>
				<a href="https://blok.build" rel="noreferrer">blok.build</a>
				<span aria-hidden="true">·</span>
				<a href="https://github.com/well-prado/blok" rel="noreferrer">GitHub</a>
				<span aria-hidden="true">·</span>
				<a href="https://deskree.com" rel="noreferrer">Deskree</a>
			</div>
		</footer>
	</div>
</template>
