// templates/spa-svelte/src/components/AppLayout.svelte
<script lang="ts">
/**
 * The persistent layout. Inertia keeps this component MOUNTED across visits
 * (each page exports `layout` from its `<script module>` block), so the header
 * and the theme toggle survive navigation — only the page below swaps.
 *
 * The page's own props are spread onto the layout too, which is how `auth`
 * reaches the header without a store.
 */
import { Link, page } from "@inertiajs/svelte";
import type { Snippet } from "svelte";
import { toggleTheme } from "../styles/theme.js";
import BlokLogo from "./BlokLogo.svelte";

interface NavItem {
	href: string;
	label: string;
	external?: boolean;
}

const NAV: NavItem[] = [
	{ href: "/", label: "Home" },
	{ href: "https://blok.build", label: "Docs", external: true },
	{ href: "https://github.com/well-prado/blok", label: "GitHub", external: true },
];

/**
 * `auth` is shaped by `@blokjs/auth`'s `currentUser` node — the same shape the
 * `--kit auth` scaffold and the plain one both publish, so this header needs no
 * kit-specific variant.
 */
const { children, auth }: { children?: Snippet; auth?: { user?: { name?: string; email?: string } | null } } = $props();

const user = $derived(auth?.user ?? null);
const label = $derived(user ? (user.name ?? user.email) : undefined);

/**
 * The 375px menu is a native `<details>` inside a PERSISTENT layout, so an
 * Inertia visit swaps the page underneath it and leaves it open, covering the
 * page it just navigated to. One line closes it; nothing else here needs JS.
 */
function closeMenu(event: MouseEvent): void {
	(event.currentTarget as HTMLElement | null)?.closest("details")?.removeAttribute("open");
}
</script>

{#snippet navLinks()}
	{#each NAV as item (item.href)}
		{#if item.external}
			<a href={item.href} rel="noreferrer" onclick={closeMenu}>{item.label}</a>
		{:else}
			<Link href={item.href} aria-current={page.url === item.href ? "page" : undefined} onclick={closeMenu}>
				{item.label}
			</Link>
		{/if}
	{/each}
{/snippet}

<!--
	Sign out is a POST (`<Link method="post">`, a real form submit), never an
	`<a href>`: a GET logout is CSRF-able and gets pre-fetched. It renders only
	when someone is signed in — the plain scaffold has no `/logout` route, and its
	`current-user` node always answers `null`.
-->
{#snippet signOut()}
	{#if user}
		<Link href="/logout" method="post" as="button" class="blok-btn blok-btn--ghost">Sign out</Link>
	{/if}
{/snippet}

<div class="blok-shell">
	<header class="blok-header">
		<div class="blok-container blok-header__inner">
			<Link href="/" class="blok-brand" aria-label="Blok — home">
				<BlokLogo height={22} />
			</Link>

			<nav class="blok-nav" aria-label="Primary">
				{@render navLinks()}
			</nav>

			<div class="blok-header__end">
				{#if label}
					<span class="blok-user">{label}</span>
				{/if}
				{@render signOut()}
				<button
					type="button"
					class="blok-btn blok-btn--ghost blok-btn--icon blok-theme-toggle"
					aria-label="Switch between light and dark theme"
					onclick={() => toggleTheme()}
				>
					<svg
						class="blok-icon--moon"
						width="16"
						height="16"
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						aria-hidden="true"
					>
						<path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79Z" />
					</svg>
					<svg
						class="blok-icon--sun"
						width="16"
						height="16"
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						aria-hidden="true"
					>
						<circle cx="12" cy="12" r="4" />
						<path
							d="M12 2v2m0 16v2M4.93 4.93l1.41 1.41m11.32 11.32 1.41 1.41M2 12h2m16 0h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"
						/>
					</svg>
				</button>

				<!-- A native <details>: the 375px menu ships no JavaScript. -->
				<details class="blok-menu">
					<summary class="blok-btn blok-btn--ghost blok-btn--icon" aria-label="Menu">
						<svg
							width="16"
							height="16"
							viewBox="0 0 24 24"
							stroke="currentColor"
							stroke-width="2"
							stroke-linecap="round"
							aria-hidden="true"
						>
							<path d="M3 6h18M3 12h18M3 18h18" />
						</svg>
					</summary>
					<div class="blok-menu__panel">
						{#if label}
							<p class="blok-menu__user">{label}</p>
						{/if}
						<nav class="blok-nav" aria-label="Primary, compact">
							{@render navLinks()}
						</nav>
						{@render signOut()}
					</div>
				</details>
			</div>
		</div>
	</header>

	<main class="blok-main">
		<div class="blok-container">{@render children?.()}</div>
	</main>

	<footer class="blok-footer">
		<div class="blok-container blok-footer__inner">
			<BlokLogo variant="mark" height={16} />
			<span>Built with Blok</span>
			<span aria-hidden="true">·</span>
			<a href="https://blok.build" rel="noreferrer">blok.build</a>
			<span aria-hidden="true">·</span>
			<a href="https://github.com/well-prado/blok" rel="noreferrer">GitHub</a>
			<span aria-hidden="true">·</span>
			<a href="https://deskree.com" rel="noreferrer">Deskree</a>
		</div>
	</footer>
</div>

// templates/spa-react/src/components/AppLayout.tsx
import { Link, usePage } from "@inertiajs/react";
import type { MouseEvent, ReactNode } from "react";
import { toggleTheme } from "../styles/theme.js";
import { BlokLogo, ThemeIcons } from "./BlokLogo.js";

/**
 * The persistent layout. Inertia keeps this component MOUNTED across visits
 * (`Page.layout = (page) => <AppLayout>{page}</AppLayout>`), so the header,
 * the theme toggle and any state they hold survive navigation — only the page
 * below swaps.
 */

interface NavItem {
	href: string;
	label: string;
	external?: boolean;
}

/** Your app's primary nav. Add a route here and the 375px menu gets it too. */
const NAV: NavItem[] = [
	{ href: "/", label: "Home" },
	{ href: "https://blok.build", label: "Docs", external: true },
	{ href: "https://github.com/well-prado/blok", label: "GitHub", external: true },
];

/**
 * The 375px menu is a native `<details>` inside a PERSISTENT layout, so an
 * Inertia visit swaps the page underneath it and leaves it open, covering the
 * page it just navigated to. One line closes it; nothing else here needs JS.
 */
function closeMenu(event: MouseEvent<Element>): void {
	event.currentTarget.closest("details")?.removeAttribute("open");
}

function navLinks(url: string): ReactNode {
	return NAV.map((item) =>
		item.external === true ? (
			<a key={item.href} href={item.href} rel="noreferrer" onClick={closeMenu}>
				{item.label}
			</a>
		) : (
			<Link key={item.href} href={item.href} onClick={closeMenu} aria-current={url === item.href ? "page" : undefined}>
				{item.label}
			</Link>
		),
	);
}

/**
 * The signed-in user, as `@blokjs/auth`'s `currentUser` node shapes it — the
 * same shape the `--kit auth` scaffold and the plain one both publish, so this
 * header needs no kit-specific variant.
 */
interface AuthProp {
	user?: { name?: string; email?: string } | null;
}

/**
 * Sign out is a POST, so it is a `<Link method="post">` (a real form submit),
 * never an `<a href>`: a GET logout is CSRF-able and gets pre-fetched by
 * browsers and link scanners.
 *
 * It renders only when someone is signed in — the plain scaffold has no
 * `/logout` route, and its `current-user` node always answers `null`.
 */
function SignOut({ user }: { user: AuthProp["user"] }): ReactNode {
	if (!user) return null;
	return (
		<Link href="/logout" method="post" as="button" className="blok-btn blok-btn--ghost">
			Sign out
		</Link>
	);
}

export function AppLayout({ children }: { children: ReactNode }) {
	const { url, props } = usePage<{ auth?: AuthProp }>();
	const user = props.auth?.user ?? null;
	const email = user === null ? undefined : (user.name ?? user.email);

	return (
		<div className="blok-shell">
			<header className="blok-header">
				<div className="blok-container blok-header__inner">
					<Link href="/" className="blok-brand" aria-label="Blok — home">
						<BlokLogo height={22} />
					</Link>

					<nav className="blok-nav" aria-label="Primary">
						{navLinks(url)}
					</nav>

					<div className="blok-header__end">
						{email === undefined ? null : <span className="blok-user">{email}</span>}
						<SignOut user={user} />
						<button
							type="button"
							className="blok-btn blok-btn--ghost blok-btn--icon blok-theme-toggle"
							onClick={() => toggleTheme()}
							aria-label="Switch between light and dark theme"
						>
							<ThemeIcons />
						</button>

						{/* A native <details>: the 375px menu ships no JavaScript. */}
						<details className="blok-menu">
							<summary className="blok-btn blok-btn--ghost blok-btn--icon" aria-label="Menu">
								<svg
									width="16"
									height="16"
									viewBox="0 0 24 24"
									stroke="currentColor"
									strokeWidth="2"
									strokeLinecap="round"
									aria-hidden="true"
								>
									<path d="M3 6h18M3 12h18M3 18h18" />
								</svg>
							</summary>
							<div className="blok-menu__panel">
								{email === undefined ? null : <p className="blok-menu__user">{email}</p>}
								<nav className="blok-nav" aria-label="Primary, compact">
									{navLinks(url)}
								</nav>
								<SignOut user={user} />
							</div>
						</details>
					</div>
				</div>
			</header>

			<main className="blok-main">
				<div className="blok-container">{children}</div>
			</main>

			<footer className="blok-footer">
				<div className="blok-container blok-footer__inner">
					<BlokLogo variant="mark" height={16} />
					<span>Built with Blok</span>
					<span aria-hidden="true">·</span>
					<a href="https://blok.build" rel="noreferrer">
						blok.build
					</a>
					<span aria-hidden="true">·</span>
					<a href="https://github.com/well-prado/blok" rel="noreferrer">
						GitHub
					</a>
					<span aria-hidden="true">·</span>
					<a href="https://deskree.com" rel="noreferrer">
						Deskree
					</a>
				</div>
			</footer>
		</div>
	);
}

/** Sugar for `Page.layout = …` — one import per page instead of two. */
export const appLayout = (page: ReactNode): ReactNode => <AppLayout>{page}</AppLayout>;
