// examples/inertia-react/client/src/pages/Dashboard.tsx
import type { PageProps } from "@blokjs/inertia";
import { Deferred, Head, InfiniteScroll, Link, WhenVisible } from "@inertiajs/react";
import type { ReactNode } from "react";
import type { Dashboard as DashboardPage } from "../../../src/workflows/dashboard.js";
import { appLayout } from "../components/AppLayout.js";

/**
 * Props come straight from the page contract — `optional` and `defer` keys are
 * `T | undefined`, everything else is present. No `ctx`, no embedding: a page
 * gets the props it declared and nothing else.
 *
 * Every tile and panel below is labelled with the PROP MODE behind it, because
 * that is the thing this example exists to show: the layout is ordinary markup
 * over `blok.css`, and the interesting part is which prop arrived when.
 */
export default function Dashboard({ auth, orders, stats, plans, posts }: PageProps<typeof DashboardPage>) {
	const revenue = orders.reduce((sum, order) => sum + order.total, 0);
	// No `can` prop on this page's contract, so the signed-out visitor (the
	// example's `guest=1` cookie) is the one who loses the row action.
	const canEdit = auth.id !== "";

	return (
		<>
			<Head title="Dashboard" />

			<div className="blok-page-header">
				<div>
					<p className="blok-eyebrow">Inertia · in-project mode</p>
					<h1>Dashboard</h1>
					<p className="blok-lede">
						One workflow, six props, five resolution modes — one of them computed by a Python node.
					</p>
				</div>
				<div className="blok-page-header__end">
					<Link href="/orders/new" className="blok-btn blok-btn--primary">
						New order
					</Link>
				</div>
			</div>

			<div className="blok-stats">
				{/* Deferred, and Python: announced on the full visit, fetched right
				    after. `rescue` is what the page shows when the sidecar is not
				    running — the prop is rescued and the page still renders. */}
				<div className="blok-stat">
					<p className="blok-stat__label">Revenue (Python)</p>
					<Deferred
						data="stats"
						fallback={
							<>
								<div className="blok-skeleton blok-skeleton--wide" style={{ height: "1.75rem" }} />
								<div className="blok-skeleton" style={{ width: "40%" }} />
							</>
						}
						rescue={
							<>
								<p className="blok-stat__value">—</p>
								<p className="blok-stat__delta">runtime.python3 sidecar not running</p>
							</>
						}
					>
						<p className="blok-stat__value">${stats?.revenue ?? 0}</p>
						<p className="blok-stat__delta blok-stat__delta--up">defer() · runtime.python3</p>
					</Deferred>
				</div>

				<StatTile label="Orders" value={orders.length} delta="regular prop" />
				<StatTile label="Order value" value={`$${revenue}`} delta="derived on the client" up />
				<StatTile label="Posts" value={posts.total} delta={`scroll() · ${posts.perPage} per page`} />
			</div>

			<div className="blok-card">
				<div className="blok-card__header">
					<h2>Orders</h2>
					<span className="blok-badge">regular</span>
				</div>
				<div className="blok-table-wrap">
					<table className="blok-table">
						<thead>
							<tr>
								<th scope="col">Order</th>
								<th scope="col">SKU</th>
								<th scope="col" className="blok-num">
									Total
								</th>
								<th scope="col" className="blok-actions">
									<span className="blok-sr-only">Actions</span>
								</th>
							</tr>
						</thead>
						<tbody>
							{orders.map((order) => (
								<tr key={order.id}>
									<td>
										<code>{order.id}</code>
									</td>
									<td>{order.sku}</td>
									<td className="blok-num">${order.total}</td>
									<td className="blok-actions">
										{canEdit ? (
											<Link href="/orders/new" className="blok-btn blok-btn--ghost">
												Edit
											</Link>
										) : (
											<span className="blok-muted">—</span>
										)}
									</td>
								</tr>
							))}
						</tbody>
					</table>
				</div>
			</div>

			<div className="blok-card">
				<div className="blok-card__header">
					<h2>Plans</h2>
					<span className="blok-badge">once</span>
				</div>
				{/* Once: the client keeps this between visits and the node stops running. */}
				<WhenVisible
					data="plans"
					fallback={
						<div className="blok-card__body">
							<div className="blok-skeleton blok-skeleton--wide" />
							<div className="blok-skeleton" />
						</div>
					}
				>
					<ul className="blok-feed">
						{plans.map((plan) => (
							<li key={plan.id}>
								<span>{plan.id}</span>
								<span className="blok-feed__meta">${plan.price}/mo</span>
							</li>
						))}
					</ul>
				</WhenVisible>
			</div>

			<div className="blok-card">
				<div className="blok-card__header">
					<h2>Posts</h2>
					<span className="blok-badge">infinite scroll</span>
				</div>
				{/* Scroll: the client grows posts.data and replaces the cursors. */}
				<InfiniteScroll
					data="posts"
					loading={
						<p className="blok-end-of-list">
							<span className="blok-spinner" /> Loading more posts…
						</p>
					}
					next={({ hasMore }) =>
						hasMore ? null : <p className="blok-end-of-list">That is all {posts.total} posts.</p>
					}
				>
					<ul className="blok-feed">
						{posts.data.map((post) => (
							<li key={post.id}>
								<span>{post.title}</span>
								<span className="blok-feed__meta">{post.id}</span>
							</li>
						))}
					</ul>
				</InfiniteScroll>
			</div>
		</>
	);
}

function StatTile({
	label,
	value,
	delta,
	up = false,
}: {
	label: string;
	value: ReactNode;
	delta: string;
	up?: boolean;
}) {
	return (
		<div className="blok-stat">
			<p className="blok-stat__label">{label}</p>
			<p className="blok-stat__value">{value}</p>
			<p className={up ? "blok-stat__delta blok-stat__delta--up" : "blok-stat__delta"}>{delta}</p>
		</div>
	);
}

// The persistent layout: Inertia keeps <AppLayout> mounted across visits.
Dashboard.layout = appLayout;

// examples/inertia-vue/client/src/pages/Dashboard.vue
<script setup lang="ts">
import type { PageProps } from "@blokjs/inertia";
import { Deferred, Head, InfiniteScroll } from "@inertiajs/vue3";
import { computed } from "vue";
import type { Dashboard } from "../../../src/workflows/dashboard.js";
import AppLayout from "../components/AppLayout.vue";

// The page contract types the stock macro — no Blok wrapper component.
const props = defineProps<PageProps<typeof Dashboard>>();

// Inertia keeps the layout MOUNTED across visits; only this page swaps.
defineOptions({ layout: AppLayout });

const orderValue = computed(() => props.orders.reduce((sum, order) => sum + order.total, 0));
</script>

<template>
	<Head title="Dashboard" />

	<div class="blok-page-header">
		<div>
			<p class="blok-eyebrow">Inertia · Vue 3</p>
			<h1>Dashboard</h1>
			<p class="blok-lede">The same page contract as the React example, rendered by a Vue client.</p>
		</div>
	</div>

	<div class="blok-stats">
		<div class="blok-stat">
			<p class="blok-stat__label">Revenue</p>
			<Deferred data="stats">
				<template #fallback>
					<div class="blok-skeleton blok-skeleton--wide" style="height: 1.75rem" />
					<div class="blok-skeleton" style="width: 40%" />
				</template>
				<!-- The prop is `defer(..., { rescue: true })`: when the node fails the
				     page still renders, and THIS is what the tile shows instead of "$". -->
				<template #rescue>
					<p class="blok-stat__value">—</p>
					<p class="blok-stat__delta">stats node unavailable</p>
				</template>
				<p class="blok-stat__value">${{ props.stats?.revenue }}</p>
				<p class="blok-stat__delta blok-stat__delta--up">defer() · fetched after the first paint</p>
			</Deferred>
		</div>
		<div class="blok-stat">
			<p class="blok-stat__label">Orders</p>
			<p class="blok-stat__value">{{ props.orders.length }}</p>
			<p class="blok-stat__delta">regular prop</p>
		</div>
		<div class="blok-stat">
			<p class="blok-stat__label">Order value</p>
			<p class="blok-stat__value">${{ orderValue }}</p>
			<p class="blok-stat__delta blok-stat__delta--up">derived on the client</p>
		</div>
		<div class="blok-stat">
			<p class="blok-stat__label">Posts</p>
			<p class="blok-stat__value">{{ props.posts.total }}</p>
			<p class="blok-stat__delta">scroll() · {{ props.posts.perPage }} per page</p>
		</div>
	</div>

	<div class="blok-card">
		<div class="blok-card__header">
			<h2>Orders</h2>
			<span class="blok-badge">regular</span>
		</div>
		<div class="blok-table-wrap">
			<table class="blok-table">
				<thead>
					<tr>
						<th scope="col">Order</th>
						<th scope="col">SKU</th>
						<th scope="col" class="blok-num">Total</th>
					</tr>
				</thead>
				<tbody>
					<tr v-for="order in props.orders" :key="order.id">
						<td>
							<code>{{ order.id }}</code>
						</td>
						<td>{{ order.sku }}</td>
						<td class="blok-num">${{ order.total }}</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>

	<div class="blok-card">
		<div class="blok-card__header">
			<h2>Posts</h2>
			<span class="blok-badge">infinite scroll</span>
		</div>
		<InfiniteScroll data="posts">
			<ul class="blok-feed">
				<li v-for="post in props.posts.data" :key="post.id">
					<span>{{ post.title }}</span>
					<span class="blok-feed__meta">{{ post.id }}</span>
				</li>
			</ul>
			<template #loading>
				<p class="blok-end-of-list"><span class="blok-spinner" /> Loading more posts…</p>
			</template>
			<template #next="{ hasMore }">
				<p v-if="!hasMore" class="blok-end-of-list">That is all {{ props.posts.total }} posts.</p>
			</template>
		</InfiniteScroll>
	</div>
</template>
