// templates/spa-react/kits/auth/src/pages/Auth/Login.tsx
import { Head, Link, useForm } from "@inertiajs/react";
import { guestLayout } from "../../components/GuestLayout.js";

/**
 * `Auth/Login` — the sign-in form (#1018).
 *
 * An ordinary Inertia form posting to the kit's `POST /login` workflow.
 * Everything Blok-specific is on the server: `@blokjs/validate` checks the
 * body, `@blokjs/auth`'s `login` node verifies the password (throttled per
 * IP + email), starts a fresh session and answers 303. A failure redirects
 * back with `props.errors.email` — which is what `form.errors.email` reads.
 */
export default function Login() {
	const form = useForm("post", "/login", { email: "", password: "", remember: false });

	return (
		<>
			<Head title="Sign in" />

			<h1>Sign in</h1>
			<p className="blok-lede">Welcome back.</p>

			<form
				className="blok-form"
				onSubmit={(event) => {
					event.preventDefault();
					form.post("/login", { onFinish: () => form.reset("password") });
				}}
			>
				<div className="blok-field">
					<label className="blok-label" htmlFor="email">
						Email
					</label>
					<input
						id="email"
						name="email"
						type="email"
						autoComplete="username"
						className="blok-input"
						placeholder="you@example.com"
						value={form.data.email}
						onChange={(event) => form.setData("email", event.target.value)}
						aria-invalid={form.errors.email === undefined ? undefined : true}
						aria-describedby={form.errors.email === undefined ? undefined : "email-error"}
					/>
					{form.errors.email === undefined ? null : (
						<p className="blok-error" id="email-error">
							{form.errors.email}
						</p>
					)}
				</div>

				<div className="blok-field">
					<label className="blok-label" htmlFor="password">
						Password
					</label>
					<input
						id="password"
						name="password"
						type="password"
						autoComplete="current-password"
						className="blok-input"
						value={form.data.password}
						onChange={(event) => form.setData("password", event.target.value)}
						aria-invalid={form.errors.password === undefined ? undefined : true}
						aria-describedby={form.errors.password === undefined ? undefined : "password-error"}
					/>
					{form.errors.password === undefined ? null : (
						<p className="blok-error" id="password-error">
							{form.errors.password}
						</p>
					)}
				</div>

				<div className="blok-guest__row">
					<label className="blok-check" htmlFor="remember">
						<input
							id="remember"
							name="remember"
							type="checkbox"
							checked={form.data.remember}
							onChange={(event) => form.setData("remember", event.target.checked)}
						/>
						Remember me
					</label>
					<Link href="/forgot-password">Forgot your password?</Link>
				</div>

				<div className="blok-form__actions">
					<button type="submit" className="blok-btn blok-btn--primary" disabled={form.processing}>
						{form.processing ? <span className="blok-spinner" /> : null}
						{form.processing ? "Signing in…" : "Sign in"}
					</button>
					<Link href="/register" className="blok-btn">
						Create an account
					</Link>
				</div>
			</form>
		</>
	);
}

Login.layout = guestLayout;

// templates/spa-svelte/kits/auth/src/pages/Auth/Login.svelte
<script module lang="ts">
// Inertia keeps the layout MOUNTED across visits; only this page swaps.
export { default as layout } from "../../components/GuestLayout.svelte";
</script>

<script lang="ts">
/**
 * `Auth/Login` — the sign-in form (#1018).
 *
 * An ordinary Inertia form posting to the kit's `POST /login` workflow.
 * Everything Blok-specific is on the server: `@blokjs/validate` checks the
 * body, `@blokjs/auth`'s `login` node verifies the password (throttled per
 * IP + email), starts a fresh session and answers 303. A failure redirects
 * back with `props.errors.email` — which is what `form.errors.email` reads.
 */
import { Link, useForm } from "@inertiajs/svelte";
import { pageTitle } from "../../title.js";

const form = useForm("post", "/login", { email: "", password: "", remember: false });

function submit(event: SubmitEvent): void {
	event.preventDefault();
	form.post("/login", { onFinish: () => form.reset("password") });
}
</script>

<svelte:head><title>{pageTitle("Sign in")}</title></svelte:head>

<h1>Sign in</h1>
<p class="blok-lede">Welcome back.</p>

<form class="blok-form" onsubmit={submit}>
	<div class="blok-field">
		<label class="blok-label" for="email">Email</label>
		<input
			id="email"
			name="email"
			type="email"
			autocomplete="username"
			class="blok-input"
			placeholder="you@example.com"
			bind:value={form.email}
			aria-invalid={form.errors.email ? true : undefined}
			aria-describedby={form.errors.email ? "email-error" : undefined}
		/>
		{#if form.errors.email}
			<p class="blok-error" id="email-error">{form.errors.email}</p>
		{/if}
	</div>

	<div class="blok-field">
		<label class="blok-label" for="password">Password</label>
		<input
			id="password"
			name="password"
			type="password"
			autocomplete="current-password"
			class="blok-input"
			bind:value={form.password}
			aria-invalid={form.errors.password ? true : undefined}
			aria-describedby={form.errors.password ? "password-error" : undefined}
		/>
		{#if form.errors.password}
			<p class="blok-error" id="password-error">{form.errors.password}</p>
		{/if}
	</div>

	<div class="blok-guest__row">
		<label class="blok-check" for="remember">
			<input id="remember" name="remember" type="checkbox" bind:checked={form.remember} />
			Remember me
		</label>
		<Link href="/forgot-password">Forgot your password?</Link>
	</div>

	<div class="blok-form__actions">
		<button type="submit" class="blok-btn blok-btn--primary" disabled={form.processing}>
			{#if form.processing}<span class="blok-spinner"></span>{/if}
			{form.processing ? "Signing in…" : "Sign in"}
		</button>
		<Link href="/register" class="blok-btn">Create an account</Link>
	</div>
</form>
