// templates/spa-svelte/kits/auth/src/pages/Auth/Register.svelte
<script module lang="ts">
// Inertia keeps the layout MOUNTED across visits; only this page swaps.
export { default as layout } from "../../components/GuestLayout.svelte";
</script>

<script lang="ts">
/**
 * `Auth/Register` — create an account (#1018).
 *
 * The field names are the kit's `RegisterSchema` (`@blokjs/auth`): rename one
 * here and the server's error keys stop matching. Success starts a session and
 * lands on `/dashboard`; a duplicate address comes back as `errors.email`.
 */
import { Link, useForm } from "@inertiajs/svelte";
import { pageTitle } from "../../title.js";

const form = useForm("post", "/register", {
	name: "",
	email: "",
	password: "",
	passwordConfirmation: "",
});

function submit(event: SubmitEvent): void {
	event.preventDefault();
	form.post("/register", { onFinish: () => form.reset("password", "passwordConfirmation") });
}
</script>

<svelte:head><title>{pageTitle("Create an account")}</title></svelte:head>

<h1>Create an account</h1>
<p class="blok-lede">Takes a moment. No email confirmation in the scaffold.</p>

<form class="blok-form" onsubmit={submit}>
	<div class="blok-field">
		<label class="blok-label" for="name">Name</label>
		<input
			id="name"
			name="name"
			autocomplete="name"
			class="blok-input"
			bind:value={form.name}
			aria-invalid={form.errors.name ? true : undefined}
			aria-describedby={form.errors.name ? "name-error" : undefined}
		/>
		{#if form.errors.name}
			<p class="blok-error" id="name-error">{form.errors.name}</p>
		{/if}
	</div>

	<div class="blok-field">
		<label class="blok-label" for="email">Email</label>
		<input
			id="email"
			name="email"
			type="email"
			autocomplete="username"
			class="blok-input"
			placeholder="you@example.com"
			bind:value={form.email}
			aria-invalid={form.errors.email ? true : undefined}
			aria-describedby={form.errors.email ? "email-error" : undefined}
		/>
		{#if form.errors.email}
			<p class="blok-error" id="email-error">{form.errors.email}</p>
		{/if}
	</div>

	<div class="blok-field">
		<label class="blok-label" for="password">Password</label>
		<input
			id="password"
			name="password"
			type="password"
			autocomplete="new-password"
			class="blok-input"
			bind:value={form.password}
			aria-invalid={form.errors.password ? true : undefined}
			aria-describedby={form.errors.password ? "password-error" : "password-hint"}
		/>
		{#if form.errors.password}
			<p class="blok-error" id="password-error">{form.errors.password}</p>
		{:else}
			<p class="blok-hint" id="password-hint">At least 8 characters.</p>
		{/if}
	</div>

	<div class="blok-field">
		<label class="blok-label" for="passwordConfirmation">Confirm password</label>
		<input
			id="passwordConfirmation"
			name="passwordConfirmation"
			type="password"
			autocomplete="new-password"
			class="blok-input"
			bind:value={form.passwordConfirmation}
			aria-invalid={form.errors.passwordConfirmation ? true : undefined}
			aria-describedby={form.errors.passwordConfirmation ? "confirm-error" : undefined}
		/>
		{#if form.errors.passwordConfirmation}
			<p class="blok-error" id="confirm-error">{form.errors.passwordConfirmation}</p>
		{/if}
	</div>

	<div class="blok-form__actions">
		<button type="submit" class="blok-btn blok-btn--primary" disabled={form.processing}>
			{#if form.processing}<span class="blok-spinner"></span>{/if}
			{form.processing ? "Creating…" : "Create account"}
		</button>
		<Link href="/login" class="blok-btn">I already have one</Link>
	</div>
</form>

// templates/spa-react/kits/auth/src/pages/Auth/Register.tsx
import { Head, Link, useForm } from "@inertiajs/react";
import { guestLayout } from "../../components/GuestLayout.js";

/**
 * `Auth/Register` — create an account (#1018).
 *
 * The field names are the kit's `RegisterSchema` (`@blokjs/auth`): rename one
 * here and the server's error keys stop matching. Success starts a session and
 * lands on `/dashboard`; a duplicate address comes back as `errors.email`.
 */
export default function Register() {
	const form = useForm("post", "/register", {
		name: "",
		email: "",
		password: "",
		passwordConfirmation: "",
	});

	return (
		<>
			<Head title="Create an account" />

			<h1>Create an account</h1>
			<p className="blok-lede">Takes a moment. No email confirmation in the scaffold.</p>

			<form
				className="blok-form"
				onSubmit={(event) => {
					event.preventDefault();
					form.post("/register", { onFinish: () => form.reset("password", "passwordConfirmation") });
				}}
			>
				<div className="blok-field">
					<label className="blok-label" htmlFor="name">
						Name
					</label>
					<input
						id="name"
						name="name"
						autoComplete="name"
						className="blok-input"
						value={form.data.name}
						onChange={(event) => form.setData("name", event.target.value)}
						aria-invalid={form.errors.name === undefined ? undefined : true}
						aria-describedby={form.errors.name === undefined ? undefined : "name-error"}
					/>
					{form.errors.name === undefined ? null : (
						<p className="blok-error" id="name-error">
							{form.errors.name}
						</p>
					)}
				</div>

				<div className="blok-field">
					<label className="blok-label" htmlFor="email">
						Email
					</label>
					<input
						id="email"
						name="email"
						type="email"
						autoComplete="username"
						className="blok-input"
						placeholder="you@example.com"
						value={form.data.email}
						onChange={(event) => form.setData("email", event.target.value)}
						aria-invalid={form.errors.email === undefined ? undefined : true}
						aria-describedby={form.errors.email === undefined ? undefined : "email-error"}
					/>
					{form.errors.email === undefined ? null : (
						<p className="blok-error" id="email-error">
							{form.errors.email}
						</p>
					)}
				</div>

				<div className="blok-field">
					<label className="blok-label" htmlFor="password">
						Password
					</label>
					<input
						id="password"
						name="password"
						type="password"
						autoComplete="new-password"
						className="blok-input"
						value={form.data.password}
						onChange={(event) => form.setData("password", event.target.value)}
						aria-invalid={form.errors.password === undefined ? undefined : true}
						aria-describedby={form.errors.password === undefined ? "password-hint" : "password-error"}
					/>
					{form.errors.password === undefined ? (
						<p className="blok-hint" id="password-hint">
							At least 8 characters.
						</p>
					) : (
						<p className="blok-error" id="password-error">
							{form.errors.password}
						</p>
					)}
				</div>

				<div className="blok-field">
					<label className="blok-label" htmlFor="passwordConfirmation">
						Confirm password
					</label>
					<input
						id="passwordConfirmation"
						name="passwordConfirmation"
						type="password"
						autoComplete="new-password"
						className="blok-input"
						value={form.data.passwordConfirmation}
						onChange={(event) => form.setData("passwordConfirmation", event.target.value)}
						aria-invalid={form.errors.passwordConfirmation === undefined ? undefined : true}
						aria-describedby={form.errors.passwordConfirmation === undefined ? undefined : "confirm-error"}
					/>
					{form.errors.passwordConfirmation === undefined ? null : (
						<p className="blok-error" id="confirm-error">
							{form.errors.passwordConfirmation}
						</p>
					)}
				</div>

				<div className="blok-form__actions">
					<button type="submit" className="blok-btn blok-btn--primary" disabled={form.processing}>
						{form.processing ? <span className="blok-spinner" /> : null}
						{form.processing ? "Creating…" : "Create account"}
					</button>
					<Link href="/login" className="blok-btn">
						I already have one
					</Link>
				</div>
			</form>
		</>
	);
}

Register.layout = guestLayout;
