// examples/inertia-react/client/src/pages/Errors/Error.tsx
import { Head, Link } from "@inertiajs/react";
import { appLayout } from "../../components/AppLayout.js";

interface Props {
	status: number;
	message: string;
}

/**
 * The production error page. Props are `{ status, message }`, where `message`
 * is the status's standard reason phrase — never the thrown error's message.
 * The one-line help below is chosen from the status, so a 404 and a 500 do not
 * read as the same event to the person looking at them.
 */
const HELP: Record<number, string> = {
	403: "You are signed in, but this page is not yours to open.",
	404: "The link may be out of date, or that route does not exist yet.",
	500: "Something broke on the server. The failure was logged — try again in a moment.",
	503: "Blok is restarting or under maintenance. This usually clears in a few seconds.",
};

export default function ErrorPage({ status, message }: Props) {
	return (
		<>
			<Head title={`${status} ${message}`} />
			<div className="blok-error-page">
				<div>
					<p className="blok-error-page__status">{status}</p>
					<h1>{message}</h1>
					<p>{HELP[status] ?? "That request could not be completed."}</p>
					<Link href="/" className="blok-btn blok-btn--primary">
						Back to dashboard
					</Link>
				</div>
			</div>
		</>
	);
}

ErrorPage.layout = appLayout;

// templates/spa-svelte/src/pages/Errors/Error.svelte
<script module lang="ts">
export { default as layout } from "../../components/AppLayout.svelte";
</script>

<script lang="ts">
/**
 * The default production error component (#1014). `@blokjs/inertia` renders
 * `Errors/Error` for 403/404/500/503 with exactly these two props — it is NOT
 * a `definePage()` contract, so it is typed inline. `message` is the status's
 * standard reason phrase, never the thrown error's message.
 */
import { Link } from "@inertiajs/svelte";

const { status, message }: { status: number; message: string } = $props();

const HELP: Record<number, string> = {
	403: "You are signed in, but this page is not yours to open.",
	404: "The link may be out of date, or that route does not exist yet.",
	500: "Something broke on the server. The failure was logged — try again in a moment.",
	503: "The app is restarting or under maintenance. This usually clears in a few seconds.",
};

const help = $derived(HELP[status] ?? "That request could not be completed.");
</script>

<svelte:head>
	<title>{status} {message}</title>
</svelte:head>

<div class="blok-error-page">
	<div>
		<p class="blok-error-page__status">{status}</p>
		<h1>{message}</h1>
		<p>{help}</p>
		<Link href="/" class="blok-btn blok-btn--primary">Back home</Link>
	</div>
</div>
